# This is a generated file. Not intended for manual editing.
services:
  expensetracker.api:
    build:
      context: "/home/roma/Projects/ExpenseTracker"
      dockerfile: "ExpenseTracker.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57406"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "romansakh14/expense_tracker:dev"
    ports:
    - "127.0.0.1:57006:57000"
    - "127.0.0.1:57206:57200"
    - "127.0.0.1:57406:57406"
    volumes:
    - "/home/roma/Projects/ExpenseTracker/ExpenseTracker.Api:/app:rw"
    - "/home/roma/Projects/ExpenseTracker:/src:rw"
    - "/home/roma/.nuget/packages:/home/app/.nuget/packages"
    - "/home/roma/.local/share/JetBrains/RiderRemoteDebugger/2025.2.4/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/655/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/roma/.cache/JetBrains/Rider2025.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_11_01_15_45_55:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
