networks:
  expense_tracker_network:
    driver: bridge
  nginxproxy_default:
    external: true

volumes:
  expense_tracker_data:

services:
  expensetracker.api:
    image: romansakh14/expense_tracker:latest
    container_name: expense_tracker_api
    restart: always
    build:
      context: .
      dockerfile: ExpenseTracker.Api/Dockerfile
    environment:
      - JWTSettings__Key=${JWTSettings__Key}
      - JWTSettings__Issuer=${JWTSettings__Issuer}
      - JWTSettings__Audience=${JWTSettings__Audience}
      - JWTSettings__ExpireTime=${JWTSettings__ExpireTime}
      - RabbitMqSettings__Host=${RabbitMqSettings__Host}
      - RabbitMqSettings__Port=${RabbitMqSettings__Port}
      - RabbitMqSettings__Username=${RabbitMqSettings__Username}
      - RabbitMqSettings__Password=${RabbitMqSettings__Password}
      - RabbitMqSettings__VirtualHost=${RabbitMqSettings__VirtualHost}
      - ConnectionStrings__PostgresqlDbConnection=${ConnectionStrings__PostgresqlDbConnection}
    ports:
      - "8080:8080"
    networks:
      - expense_tracker_network
      - nginxproxy_default
    depends_on:
      - postgres_db
      - broker
    
  postgres_db:
    image: postgres:17
    container_name: expense_tracker_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DbSettings__Password}
      POSTGRES_USER: ${DbSettings__User}
    ports:
      - "5432:5432"
    volumes:
      - expense_tracker_data:/var/lib/postgresql/data
    networks:
      - expense_tracker_network
    
  broker:
    image: rabbitmq:3.13-management
    container_name: expense_tracker_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RabbitMqSettings__Username}
      - RABBITMQ_DEFAULT_PASS=${RabbitMqSettings__Password}
      - RABBITMQ_DEFAULT_VHOST=${RabbitMqSettings__VirtualHost}
    networks:
      - expense_tracker_network
      - nginxproxy_default
